version: '3.8'


services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: hchaguer
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: piscineds
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hchaguer -d piscineds"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pdgdata:/var/lib/postgresql/data
    networks:
      - dw_network

  python-runner:
    build:
      context: ../..
      dockerfile: data-warehouse/ex00/Dockerfile
    container_name: python_runner
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: piscineds
      POSTGRES_USER: hchaguer
      POSTGRES_PASSWORD: 123
    volumes:
      - .:/app/script
    networks:
      - dw_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dw_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: hchaguer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - dw_network

volumes:
  pdgdata:
    name: pdgdata
    driver: local
    driver_opts:
      type: none
      device: /Users/hchaguer/data/postgres_data
      o: bind

networks:
  dw_network: